> library(quantmod)
> library(xts)
> library(rvest)
> library(tidyverse)
> library(plotly)
> library(corrplot)
> library(dplyr)
> library(PerformanceAnalytics)
> getSymbols("YDX.BE",from="2018-01-01",to="2020-12-31")
> YDX.BE_log_returns<- YDX.BE%>%Ad()%>%dailyReturn(type='log')
> YDX.BE_mean_log<-mean(YDX.BE_log_returns)
> mean_log<-c(YDX.BE_mean_log)
> mean_log<-round(mean_log,4)
> YDX.BE_sd_log<-sd(YDX.BE_log_returns)
> sd_log<-c(YDX.BE_sd_log)
>graphic1<-data.frame(rbind(c("YDX.BE",YDX.BE_mean_log, YDX.BE_sd_log),stringsAsFactors = FALSE))
> graphic1<-data.frame(mean_log,sd_log)
> rownames(graphic1)<-c("YDX.BE")
> colnames(graphic1)<-c("Mean_Log_Return", "Sd_Log_Return")
> xlab<-list(title="Reward")
> ylab<-list(title="Risk")
> plot_ly(x=graphic1[,1],y=graphic1[, 2],text=rownames(graphic1), type='scatter',mode="markers",marker=list(color=c("black","blue","red","grey","green")))%>%layout(title="Risk v Reward",xaxis=xlab,yaxis=ylab)
> YDX.BE%>%Ad()%>%chartSeries()
> YDX.BE%>%chartSeries(TA='addBBands(); addBBands(draw="p"); addVo();addMACD()',subset='2020')
> probs<-c(0.005,0.025,0.25,0.5,0.75,0.975,0.995)
> YDX.BE_dist<-YDX.BE_log_returns%>%quantile(probs=probs, na.rm=TRUE)
> YDX.BE_mean<-mean(YDX.BE_log_returns,na.rm=TRUE)
> YDX.BE_sd<-sd(YDX.BE_log_returns,na.rm=TRUE)
> YDX.BE_mean%>%exp()
> mu<- YDX.BE_mean_log
> sig<- YDX.BE_sd_log
> testsim<-rep(NA,1000)
> price<-rep(NA,252)
> price[1]<-as.numeric(YDX.BE$YDX.BE.Adjusted[length(YDX.BE$YDX.BE.Adjusted),])
> for(i in 2:length(testsim)){price[i]<-price[i-1]*exp(rnorm(1,mu,sig))}
> random_data<-cbind(price,1:(252))
> colnames(random_data)<-c("Price","Day")
> random_data<-as.data.frame(random_data)
> random_data%>%ggplot(aes(Day,Price))+geom_line()+labs(title="Yandex (YDX.BE) price simulation for 1 year")+theme_bw()
> N<-500
> mc_matrix<-matrix(nrow=252,ncol=N)
> mc_matrix[1,1]<-as.numeric(YDX.BE$YDX.BE.Adjusted[length(YDX.BE$YDX.BE.Adjusted),])
> for(j in 1:ncol(mc_matrix)){
  mc_matrix[1,j]<-as.numeric(YDX.BE$YDX.BE.Adjusted[length(YDX.BE$YDX.BE.Adjusted),])
for(i in 2:nrow(mc_matrix)){
  mc_matrix[i,j]<-mc_matrix[i-1,j]*exp(rnorm(1,mu,sig))
}
}
> name<-str_c("Sim ",seq(1,500))
> name<-c("Day",name)
> final_mat<-cbind(1:(252),mc_matrix)
> final_mat<-as.tibble(final_mat)
> colnames(final_mat)<-name
> dim(final_mat)
> final_mat%>%gather("Simulation","Price",2:501)%>%ggplot(aes(x=Day,y=Price,Group=Simulation))+geom_line(alpha=0.2)+labs(title="Yandex Stock (YDX.BE): 500 Monte Carlo Simulations for 1 Year")+theme_bw()
